#################################################################
#                                                               #
#                      Packages/Weather                         #
#                                                               #
#################################################################

#################################################################
#                                                               #
#                          Customize                            #
#                                                               #
#################################################################

homeassistant:
  customize:

  
#################################################################
#                                                               #
#                           Group                               #
#                                                               #
#################################################################

group:

#################################################################
#                                                               #
#                           Switches                            #
#                                                               #
#################################################################

switch:
        
#################################################################
#                                                               #
#                        Input Boolean                          #
#                                                               #
#################################################################

input_boolean:        

#################################################################
#                                                               #
#                         Automations                           #
#                                                               #
#################################################################

automation:
## Runs a script to turn on morning cartoons when staircase motion is triggered after 4am
  - alias: 'Good Morning'
    trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d00022c2f21
      to: 'on'
    condition:
    - condition: state
      entity_id: input_boolean.morning_script_run
      state: 'on'
    - condition: time
      after: '04:00'
      before: '09:00'  
    action:
    - service: tts.google_say
      data:
        entity_id: media_player.tts_kodi
        message: Good Morning Team
    - service: script.1527974742281
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.morning_script_run
    