#################################################################
#                                                               #
#                     Packages/Date & Time                      #
#                                                               #
#################################################################

#################################################################
#                                                               #
#                       Binary Sensors                          #
#                                                               #
#################################################################

binary_sensor:

####################################################
#                                                  #
#            Binary Sensors - Workday              #
#                                                  #
#################################################### 

  - platform: workday
    country: AU
    workdays: [mon, tue, wed, thu, fri]
    
#################################################################
#                                                               #
#                            Sensors                            #
#                                                               #
#################################################################

sensor:

####################################################
#                                                  #
#                Sensor - Time/Date                #
#                                                  #
####################################################

  - platform: time_date
    display_options:
      - time
      - date
      - date_time
      - time_date
      - time_utc
      - beat
      
####################################################
#                                                  #
#               Sensor - World Clock               #
#                                                  #
####################################################

  - platform: worldclock
    time_zone: Australia/Sydney
    name: Claire Time
  
  - platform: worldclock
    time_zone: Europe/London
    name: Mum Time
