####################################################
#                                                  #
#                TP-Link Cameras                   #
#                                                  #
####################################################

- platform: generic
  still_image_url: !secret baby_monitor_url
  name: Baby Monitor
  username: admin
  password: !secret camera_password
  authentication: digest