#################################################################
#                                                               #
#                           Customize                           #
#                                                               #
#################################################################

#################################################################
#                                                               #
#                          UI-Lovelace                          #
#                                                               #
#################################################################

group.downstairs_lights:
  icon: mdi:lightbulb

group.windows_ll:
  icon: mdi:window-open
    