####################################################
#                                                  #
#                     Android                      #
#                                                  #
####################################################

  - name: Galaxy_Tab_A_(2016)
    platform: lannouncer
    host: ip
    
####################################################
#                                                  #
#                      Kodi                        #
#                                                  #
####################################################
   
  - platform: kodi
    host: ip   
    port: port                 
    name: TTS_Kodi                    
    username: kodi            
    password: kodi