- platform: device_tracker_sensor
  entities:
    - device_tracker.core_router
    - device_tracker.nas_movies
    - device_tracker.nas_tv
    - device_tracker.core_switch
    - device_tracker.upstairs_switch
    - device_tracker.wifi_bridge
    - device_tracker.5g_ac_main
    - device_tracker.5g_ac_media_tv
    - device_tracker.smart_things_hub
    - device_tracker.44650df543ec
    - device_tracker.f081735c7ffc
    - device_tracker.8c89a5ef4d19
    - device_tracker.printer
    - device_tracker.rpi
    - device_tracker.garden_pi
    - device_tracker.xiaomi_gateway
    - device_tracker.kitchen_dashboard
    - device_tracker.upstairs_dashboard
    - device_tracker.5g_ac_upstairs
    - device_tracker.hdhomerun
    - device_tracker.media_tv
    - device_tracker.media_kodi_4k
    - device_tracker.appletv
    - device_tracker.bedroom_tv
    - device_tracker.bedroom_kodi
    - device_tracker.patio_kodi
    - device_tracker.ir_blaster_downstairs
    - device_tracker.ir_blaster_upstairs
    - device_tracker.patio_led_switch
    - device_tracker.playroom_fan
    - device_tracker.robovac
    - device_tracker.alarm_panel